### ISSUE TITLE
Format of the output GRO file

### ISSUE THREAD

**Issue by ricalessandri** [jbarnoud/cgbuilder#1]
I found very useful also the generation of the GRO file!

However, while I was playing with coronene I found out that because the bead label gets to 6 characters then you get an output GRO which looks like this:

```
Generated with cgbuilder
12
    0CORO BEAD0    1   2.309   2.876  -0.007
    0CORO BEAD1    2  -3.645   0.562   0.005
    0CORO BEAD2    3   1.336  -3.437   0.013
    0CORO BEAD3    4  -2.309  -2.876  -0.012
    0CORO BEAD4    5  -1.336   3.437   0.008
    0CORO BEAD5    6   3.645  -0.562   0.001
    0CORO BEAD6    7  -1.669   1.339   0.003
    0CORO BEAD7    8  -0.326  -2.114  -0.002
    0CORO BEAD8    9   1.994   0.775  -0.005
    0CORO BEAD9   10  -1.994  -0.775  -0.005
    0CORO BEAD10   11   0.326   2.114  -0.003
    0CORO BEAD11   12   1.669  -1.339   0.003
10 10 10
```
which is not going to display correctly because of the last 2 atoms.

**Comment by ricalessandri** [comment]
Moreover, the obtained coordinates are not in nm (GRO format) but in angstroms. I guess that's because I fed a PDB (i.e., angstrom coordinates) to `cgbuilder`.

**Comment by jbarnoud** [comment]
Thanks for reporting the issue. It should be fixed now.
