### ISSUE TITLE
Downloadable GRO file doesn't open in VMD

### ISSUE THREAD

**Issue by ricalessandri** [jbarnoud/cgbuilder#2]
The GRO file I download won't open, while if I copy and paste the lines in an empty file and the open it it works. I attach the files.
[cgbuilder-GROs.zip](https://github.com/jbarnoud/cgbuilder/files/2016717/cgbuilder-GROs.zip)

Doing a `diff cgbuilder.gro cgbuilder-copy-and-paste.gro` in the terminal I get the following:
```
7c7
< 10 10 10
\ No newline at end of file
---
> 10 10 10
```

But I cannot see any empty line in any of the files..

**Comment by jbarnoud** [comment]
fixed in 380b1a2b3af2af00ac95e91d1829b3a75a8f4335 a new line was needed.
