### ISSUE TITLE
BEAD --> B

### ISSUE THREAD

**Issue by ricalessandri** [jbarnoud/cgbuilder#4]
The default atom label `BEAD` is a bit too long. As soon as one gets into more than 10 bead, the output `gro` file will contain truncated entries as in the following example:

```
    1PYRE BEAD0    1   x.xxx   y.yyy   z.zzz
. . .
    1PYRE BEAD8    9   x.xxx   y.yyy   z.zzz
    1PYRE BEAD9   10   x.xxx   y.yyy   z.zzz
    1PYRE BEAD1   11   x.xxx   y.yyy   z.zzz
    1PYRE BEAD1   12   x.xxx   y.yyy   z.zzz
    1PYRE BEAD1   13   x.xxx   y.yyy   z.zzz
    1PYRE BEAD1   14   x.xxx   y.yyy   z.zzz
```

**Comment by jbarnoud** [comment]
@ricalessandri It should be OK now. If you still have your beads named "BEAD", it may be because you have the old script in cache. Reload with Shift-F5 to ignore the cache.
